---
name: Build

on: # yamllint disable-line rule:truthy
  workflow_call:
    inputs:
      target:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      target:
        default: x86_64-unknown-linux-gnu
        description: target to build for (e.g. "x86_64-unknown-linux-gnu")
        type: string

env:
  RUST_BACKTRACE: full

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        # skip setup on the default toolchain
        if: inputs.target != 'x86_64-unknown-linux-gnu'
        with:
          override: true
          target: ${{ inputs.target }}
          toolchain: stable

      - uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: -C target-feature=-crt-static
        with:
          args: --release --verbose --target ${{ inputs.target }}
          command: build
          use-cross: true

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.target }}
          path: |
            target/*/release/libatc_router.a
            target/*/release/libatc_router.so
          retention-days: 5
          if-no-files-found: error
