---
name: Build

on: # yamllint disable-line rule:truthy
  pull_request:
  push:
    # branches:
    #   - main

env:
  RUST_BACKTRACE: full

jobs:
  artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        # skip setup on the default toolchain
        if: matrix.target != 'x86_64-unknown-linux-gnu-gcc'
        with:
          override: true
          target: ${{ matrix.target }}
          toolchain: stable

      - uses: actions-rs/cargo@v1
        env:
          # 1. quiet (aka allow) warnings; these were getting parsed by gha
          # 2. produce statically  linked library
          RUSTFLAGS: -Awarnings -C target-feature=-crt-static
        with:
          args: --release --target ${{ matrix.target }} --verbose
          command: build
          use-cross: true

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: |
            target/${{matrix.target}}/release/libatc_router.a
            target/${{matrix.target}}/release/libatc_router.so
          retention-days: 5
          if-no-files-found: error
