---
name: Build Target

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      target:
        default: x86_64-unknown-linux-gnu
        description: target to build for (e.g. "x86_64-unknown-linux-gnu")
        type: string
      release:
        default: false
        description: 'run cargo with --release flag (default: false)'
        type: boolean
      upload:
        default: true
        description: 'upload created .a & .so files (default: true)'
        type: boolean
  workflow_call:
    inputs:
      target:
        required: true
        type: string
      release:
        default: false
        type: boolean
      upload:
        default: true
        type: boolean

env:
  RUST_BACKTRACE: full

jobs:
  build:
    name: 'Build Target: ${{ inputs.target }}'
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.flags.outputs.release }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        # skip setup on the default toolchain
        if: inputs.target != 'x86_64-unknown-linux-gnu'
        with:
          override: true
          target: ${{ inputs.target }}
          toolchain: stable

      - name: Determine Cargo "release" Flag
        id: flags
        run: |
          if [[ '${{ inputs.release }}' == 'true' ]]; then
            echo 'release=--release' >> $GITHUB_OUTPUT
          else
            echo 'release=' >> $GITHUB_OUTPUT
          fi

      - uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: -C target-feature=-crt-static
        with:
          args: ${{ steps.flags.outputs.release }} --verbose --target ${{ inputs.target }}
          command: build
          use-cross: true

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.target }}
          path: |
            target/*/release/libatc_router.a
            target/*/release/libatc_router.so
          retention-days: 5
          if-no-files-found: error
