---
name: Build

on: # yamllint disable-line rule:truthy
  pull_request:
  push:
    # branches:
    #   - main

env:
  RUST_BACKTRACE: full

jobs:
  artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
        libc:
          - gnu
          - musl

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        # skip setup on the default toolchain
        if: ${{ (matrix.arch != 'x86_64') && (matrix.libc != 'gnu') }}
        with:
          override: true
          target: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
          toolchain: stable

      - uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: -C target-feature=-crt-static
        with:
          args: |
            --release \
            --verbose \
            --target ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
          command: build
          use-cross: true

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.arch }}-${{ matrix.libc }}
          path: |
            target/*/release/libatc_router.a
            target/*/release/libatc_router.so
          retention-days: 5
          if-no-files-found: error
