---
name: Build Targets

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
    inputs:
      upload:
        default: true
        description: 'upload created .a & .so files (default: true)'
        type: boolean
  workflow_call:
    inputs:
      upload:
        default: true
        type: boolean

jobs:
  builds:
    name: Build targets
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
        libc:
          - gnu
          - musl
    with:
      target: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
      upload: ${{ inputs.upload }}
