---
name: Build Targets

on: # yamllint disable-line rule:truthy
  workflow_call:

jobs:
  builds:
    name: Build targets
    uses: ./.github/workflows/build.yml
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
        libc:
          - gnu
          - musl
    with:
      target: ${{ matrix.arch }}-unknown-linux-${{ matrix.libc }}
